spring.datasource.url=jdbc:postgresql://localhost:5432/libri_db
spring.datasource.username=libri
spring.datasource.password=libri_secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.jwt.secret=LibriSecretKeyForJwtSigningMustBeAtLeast256BitsLong2026
app.jwt.expiration=86400000

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

server.port=8080
spring.application.name=libri-server
